name: Prepare Scratch Pools
description: Action to prepare scratch org pools
inputs:
  dev-hub:
    description: The alias of the Dev Hub org
    required: true
  sfdx-project-path:
    description: The path to sfdx-project.json
    required: false
  package-key:
    description: The key of the packages to install
    required: false
  pool-config-path:
    description: The path to the pool configuration file
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Dev Hub scratch limits
      shell: bash
      env:
        DEV_HUB: ${{ inputs.dev-hub }}
      run: bash "$GITHUB_ACTION_PATH/scripts/check_scratch_limits.sh"

    - uses: navikt/crm-workflows-base/.github/actions/createPackageKeyPairs.yml@main
      if: ${{ inputs.package-key != '' }}
      with:
        sfdx-project-path: ${{ inputs.sfdx-project-path }}
        package-key: ${{ inputs.package-key }}
      id: createPackageKeyPairs
      env:
        CRM_PACKAGE_KEY: ${{ inputs.package-key }}
        SFDX_PROJECT_PATH: ${{ inputs.sfdx-project-path }}
        DEV_HUB: ${{ inputs.dev-hub }}

    - name: Prepare pool
      shell: bash
      env:
        # Access outputs from previous step must use steps.<id>.outputs syntax
        CRM_PACKAGE_KEY_PAIRS: ${{ steps.createPackageKeyPairs.outputs.package-keys }}
        SFDX_PROJECT_PATH: ${{ inputs.sfdx-project-path }}
        POOL_CONFIG_PATH: ${{ inputs.pool-config-path }}
        DEV_HUB: ${{ inputs.dev-hub }}
      run: |
        bash "$GITHUB_ACTION_PATH/scripts/prepare_pool.sh"
