name: Prepare Scratch Pools
description: Action to prepare scratch org pools
inputs:
  dev-hub:
    description: The alias of the Dev Hub org
    required: true
  sfdx-project-path:
    description: The path to sfdx-project.json
    required: false
  package-key:
    description: The key of the packages to install
    required: false
  pool-config-path:
    description: The path to the pool configuration file
    required: true
  sfp-log-level:
    description: The log level for sfp commands
    default: "INFO"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check Dev Hub scratch limits
      shell: bash
      env:
        DEV_HUB: ${{ inputs.dev-hub }}
      run: bash "$GITHUB_ACTION_PATH/scripts/check_scratch_limits.sh"

    - uses: navikt/sf-gha-create-package-key-pairs@e832861fe2cc5e5d37a491ad0980733bd5ba55c9
      if: ${{ inputs.package-key != '' }}
      with:
        sfdx-project-path: ${{ inputs.sfdx-project-path }}
        package-key: ${{ inputs.package-key }}
        devhub-alias: ${{ inputs.dev-hub }}
      id: createPackageKeyPairs
      env:
        CRM_PACKAGE_KEY: ${{ inputs.package-key }}
        SFDX_PROJECT_PATH: ${{ inputs.sfdx-project-path }}
        DEV_HUB: ${{ inputs.dev-hub }}

    - name: Prepare pool
      shell: bash
      env:
        # Access outputs from previous step must use steps.<id>.outputs syntax
        CRM_PACKAGE_KEY_PAIRS: ${{ steps.createPackageKeyPairs.outputs.package-keys }}
        SFDX_PROJECT_PATH: ${{ inputs.sfdx-project-path }}
        POOL_CONFIG_PATH: ${{ inputs.pool-config-path }}
        DEV_HUB: ${{ inputs.dev-hub }}
        LOG_LEVEL: ${{ inputs.sfp-log-level }}
      run: |
        bash "$GITHUB_ACTION_PATH/scripts/prepare_pool.sh"
